
  CREATE TABLE "FOXFL"."FL_WIP_MOVE_ALL" 
   (	"MOVE_HEADER_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"APPLY_TIME" DATE NOT NULL ENABLE, 
	"APPLY_USER_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"RC_LINE_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"FLOW_STATUS" VARCHAR2(30) NOT NULL ENABLE, 
	"OPERATION_FM" NUMBER(10,0) NOT NULL ENABLE, 
	"OPERATION_TO" NUMBER(10,0) NOT NULL ENABLE, 
	"OVER_MOVE_FLAG" VARCHAR2(1), 
	"RETURN_FLAG" VARCHAR2(1), 
	"COMPLETE_GOOD_QTY" NUMBER, 
	"COMPLETE_NG_QTY" NUMBER, 
	"COMPLETE_PACKING_QTY" NUMBER, 
	"COMPLETE_CARTON_QTY" NUMBER, 
	"UNKNOW_QTY" NUMBER, 
	"UNKNOW_TO_GOOD_QTY" NUMBER, 
	"UNKNOW_TO_NG_QTY" NUMBER, 
	"UNKNOW_TO_PACKING_QTY" NUMBER, 
	"UNKNOW_TO_CARTON_QTY" NUMBER, 
	"WORK_HOURS" NUMBER, 
	"ORGANIZATION_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"RC_RESOURCE_ID" NUMBER(15,0), 
	"BOM_RESOURCE_ID" NUMBER(15,0), 
	"CARD_ID" NUMBER, 
	"ACTUAL_PROD_DATE" DATE, 
	"ACTUAL_CALENDAR_CODE" VARCHAR2(60), 
	"ACTUAL_SHIFT_NUM" NUMBER, 
	"MOVE_TIME_FROM" DATE, 
	"MOVE_TIME_TO" DATE, 
	"RUN_CARD_NO" VARCHAR2(30), 
	"DESCRIPTION" VARCHAR2(240), 
	"RETURN_REASON_CODE" VARCHAR2(30), 
	"RETURN_REASON" VARCHAR2(300), 
	"RESOURCE_UNITS" NUMBER, 
	"QA_SEGMENT_ID" NUMBER(15,0), 
	"QA_SEGMENT_CODE" VARCHAR2(100), 
	"DEPARTMENT_ID_FM" NUMBER(15,0), 
	"DEPARTMENT_ID_TO" NUMBER(15,0), 
	"RC_DEPARTMENT_CODE" VARCHAR2(20), 
	"INVENTORY_ITEM_ID" NUMBER(15,0), 
	"PROD_LINE_CODE" VARCHAR2(60), 
	"CALENDAR_CODE" VARCHAR2(30), 
	"SHIFT_NUM" NUMBER(15,0), 
	"WIP_ENTITY_ID" NUMBER(15,0), 
	"PROD_DATE" DATE, 
	"ACTUAL_PROD_LINE_CODE" VARCHAR2(60), 
	"RC_RESOURCE_ID2" NUMBER, 
	"FINAL_JOB_FLAG" VARCHAR2(1), 
	"MOVE_REVISION" NUMBER, 
	"SOURE_RC_TICKET_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE KEEP)
  TABLESPACE "FOXFL" 
  CREATE UNIQUE INDEX "FOXFL"."FL_WIP_MOVE_U1" ON "FOXFL"."FL_WIP_MOVE_ALL" ("MOVE_HEADER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE KEEP)
  TABLESPACE "FOXFL" 
ALTER TABLE "FOXFL"."FL_WIP_MOVE_ALL" ADD CONSTRAINT "FL_MOVE_PK" PRIMARY KEY ("MOVE_HEADER_ID")
  USING INDEX "FOXFL"."FL_WIP_MOVE_U1"  ENABLE