
  CREATE INDEX "FOXFL"."FL_GL_BUDGET_EXPAND_MST_N1" ON "FOXFL"."FL_GL_BUDGET_EXPAND_MST" ("PROJECT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE KEEP)
  TABLESPACE "APPS_TS_TX_DATA" 