
  CREATE OR REPLACE EDITIONABLE FUNCTION "APPS"."FL_AF_GET_ITEM_STATUS_F" (P_ORG_CODE IN VARCHAR2,P_ITEM_NO IN VARCHAR2 ) RETURN VARCHAR2 IS
V_CNT     NUMBER;
V_STATUS  VARCHAR2(25);
BEGIN
     SELECT COUNT(*) INTO V_CNT
    FROM FL_AF_ITEM_UPD_T T, MTL_PARAMETERS MP
    WHERE T.ORG_CODE= MP.ORGANIZATION_CODE
    AND MP.ORGANIZATION_CODE=P_ORG_CODE
    AND ITEM_NO = LTRIM(RTRIM(P_ITEM_NO)) 
    AND ERP_STATUS IS NULL ; --有空白表示ERP尚未處理,AF不可申請異動
    IF V_CNT > 0 THEN
       V_STATUS := 'In Processing' ;
    ELSE
       V_STATUS := 'OK' ;
    END IF;

  RETURN V_STATUS;
END;

 
